{% set name = "fugue-sql-antlr" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fugue-sql-antlr-{{ version }}.tar.gz
  sha256: 22af96a6aa295441425482c6619daac1702de222c942ede12b36bc2e2993aa40

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - antlr4-python3-runtime <4.12
    - jinja2
    - python >=3.8
    - triad >=0.6.8

    # Not listed upstream but required
    - packaging

test:
  imports:
    - fugue_sql_antlr
    - fugue_sql_antlr_version
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fugue-project/fugue-sql-antlr
  summary: Fugue SQL Antlr Parser
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - charlesbluca
    - kvnkho
    - goodwanghan
    - thewchan
